### ISSUE TITLE
Package does not work on Ubuntu 18.04

### ISSUE THREAD

**Issue by jamesadevine** [gwbres/systemctl#12]
Hiya!

This package works great for 20.04 onwards. On 18.04 (and before?) however, the systemctl binary is in a different location: `/bin/systemctl`.

After examining the code base, I spotted the `SYSTEMCTL_PATH` environment variable that can be set. I have tried to set the variable in a multitude of ways from my application, but the variable does not seem to take effect. I verified this by cloning and using a local copy of this library.

Ways I've tried:

* `SYSTEMCTL_PATH=/bin/systemctl cargo r -- status`
* `export SYSTEMCTL_PATH=/bin/systemctl && cargo r -- status`
* In my app using temp_var:
```
temp_env::with_var("SYSTEMCTL_PATH", Some("/bin/systemctl"), || {
    systemctl::exists(SERVICE_NAME)
})?;
```
* in my app using `env::set_var`:
```
env::set_var(key, "/bin/systemctl")
systemctl::exists(SERVICE_NAME)
```

In all cases, `default_env!` uses the default path.

**Comment by jamesadevine** [comment]
Is there something obvious I am missing here?

**Comment by jamesadevine** [comment]
The obvious thing was that `default_env!` is set at compile time. This is kinda annoying if you want to support multiple distro versions...

**Comment by alexkunde** [comment]
@jamesadevine , @gwbres the environment variable will work with the newest commit to main.
**But** it will not help you much just yet, as the systemctl version between 18.04 and 22.04 are much different.
v237 -> v249 ...
I just did a quick test and one direct thing that needs fixing is, `systemctl list-unit-files` only has two colums instead of three.
I will have a look if ubuntu 18.04 can be implemented behind a feature gate, if you would still be interested in this.

**Comment by jamesadevine** [comment]
@alexkunde Since 18.04 is now end of life, I am no longer interested! Thanks for fixing the env variable :smile:

**Comment by alexkunde** [comment]
Thank you, I'm glad to hear that. Since Github does not support 18.04 runners anymore it would have been hard to test efficiently.

Once your tests are done, can you close this issue?
